### PR TITLE
attempt to read ~/.docker/config.json for registry auths

### LINKED ISSUE #261: Cannot pull Chef image when using custom image/creds file
## :ghost: Brief Description

The `creds_file` option seems to be used for both `image` and `chef_image` (presumably `data_image`, too), which fails when mixing and matching registries.

Ideally, I think we'd want to be able to specify credentials for multiple repositories, similar to a `~/.docker/config.json`. (Even better if it could read this file directly rather than managing a separate `creds.json`.

For example:

```json
{
	"auths": {
		"my.private-registry.com": {
			"auth": "redacted"
		},
        "https://index.docker.io/v1/": {
			"auth": "redacted"
		}
	}
}

```

## Version

`kitchen-dokken (2.17.0)`

## Environment

MacOS (M1), Docker 20.10.12

## Scenario

1. Pull `chef/chef` image from DockerHub as the default `chef_image`
2. Pull `my.private-registry.com/my-custom-image` by setting a custom `image` in driver config
3. Run test kitchen as normal

When passing a creds file, the initial pull of `chef/chef` fails. When not specifying a creds file, I cannot pull my custom image.

## Steps to Reproduce

`kitchen create default` with the following `.kitchen.dokken.yml`

```yml
---
driver:
  name: dokken
  chef_version: 17
  privileged: true
  creds_file: ./creds.json

transport:
  name: dokken

provisioner:
  name: dokken
  clean_dokken_sandbox: false

verifier:
  name: inspec
  backend_cache: true

platforms:
  - name: ubuntu-18.04
    driver:
      image: my.private-registry.com/my-custom-image/dokken-ubuntu:18.04
      pid_one_command: /bin/systemd
```

`creds.json`:

```json
{
  "username": "evandam",
  "password": "REDACTED",
  "serveraddress": "my.private-registry.com"
}
```

## Expected Result

Instances is created successfully.

## Actual Result

Retries to auth and pull from `chef/chef` end up burning through my DockerHub rate limit 😅 

```
❯ kitchen create def
-----> Starting Test Kitchen (v3.2.2)
-----> Creating <default-ubuntu-1804>...
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/lockfile-2.1.3/lib/lockfile.rb:308: warning: finalizer references object to be finalized
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [{"message":"Head \"https://registry-1.docker.io/v2/chef/chef/manifests/17\": toomanyrequests: too many failed login attempts for username or IP address"}
] on default-ubuntu-1804
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## :heavy_plus_sign: Additional context

Totally possible I'm doing things wrong. Only related thing I see is https://github.com/test-kitchen/kitchen-dokken/issues/126. Thanks in advance!

### PR DESCRIPTION
**Pull request by evandam**
# Description

Rough attempt to resolve #261 by reading `~/.docker/config.json` to get auths for an image's registry rather than relying on a single `creds_file` while not breaking any existing compatibility (by introducing a new `docker_config_auth` flag). I'm sure it's far from perfect, but hoping this is a good jumping off point and folks have better ideas.

I realize `image_registry = image.split('/').first` will often be misleading especially for official images on DockerHub, but might be good enough.

Looks like there's some similar work in https://github.com/test-kitchen/kitchen-dokken/pull/189/files but not sure 🤷‍♂️ 

## Issues Resolved

Fixes #261 

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

File: lib/kitchen/driver/dokken.rb [hunk 1]
```diff
@@ -429,6 +431,33 @@ def docker_creds
                           end
       end
 
+      def docker_config_creds
+        return @docker_config_creds if @docker_config_creds
+
+        @docker_config_creds = {}
+        config_file = ::File.join(::Dir.home, ".docker", "config.json")
+        JSON.load_file!(config_file)["auths"].each do |k, v|
+          username, password = Base64.decode64(v["auth"]).split(":")
```
Comment (ashiqueps) [inline lib/kitchen/driver/dokken.rb:440]: Hi @evandam 

Whenever the config file has multiple registry entires and one of the registry doesn't have any credentials, this line will raise exception.
```ruby
E, [2022-06-01T00:05:44.812885 #32360] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2022-06-01T00:05:44.812915 #32360] ERROR -- Kitchen: Message: Failed to complete #create action: [undefined method `unpack1' for nil:NilClass

    str.unpack1("m")
       ^^^^^^^^]
E, [2022-06-01T00:05:44.812949 #32360] ERROR -- Kitchen: ----------------------
E, [2022-06-01T00:05:44.812979 #32360] ERROR -- Kitchen: ------Backtrace-------
E, [2022-06-01T00:05:44.813008 #32360] ERROR -- Kitchen: .rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/base64.rb:59:in `decode64'
E, [2022-06-01T00:05:44.813036 #32360] ERROR -- Kitchen: Projects/kitchen-dokken/lib/kitchen/driver/dokken.rb:443:in `block in docker_config_creds'
E, [2022-06-01T00:05:44.813070 #32360] ERROR -- Kitchen: Projects/kitchen-dokken/lib/kitchen/driver/dokken.rb:442:in `each'
E, [2022-06-01T00:05:44.813099 #32360] ERROR -- Kitchen: Projects/kitchen-dokken/lib/kitchen/driver/dokken.rb:442:in `docker_config_creds'
```
My config file: 
```json
{
   "auths": {
      "https://index.docker.io/v1/": {
         "auth": "BASE64Username&Password"
      },
      "icr.io": {},
      "public.ecr.aws": {}
   }
}
```

**Review by ashiqueps — CHANGES_REQUESTED** [review]

**Review by ashiqueps — APPROVED** [review]

**Comment by PJB3005** [comment]
This seems to break Kitchen if you don't have a `~/.docker/config.json` (file not found error) and then a nil value call if you don't have an `auths` key in it.

**Comment by evandam** [comment]
Hey folks, I opened a new PR that should address this https://github.com/test-kitchen/kitchen-dokken/pull/276
